#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v4
# autospec commit: da8b975a5699
#
Name     : perl-Test-InDistDir
Version  : 1.112071
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/M/MI/MITHALDU/Test-InDistDir-1.112071.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MI/MITHALDU/Test-InDistDir-1.112071.tar.gz
Summary  : 'test environment setup for development with IDE'
Group    : Development/Tools
License  : WTFPL
Requires: perl-Test-InDistDir-license = %{version}-%{release}
Requires: perl-Test-InDistDir-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# NAME
Test::InDistDir - test environment setup for development with IDE
# VERSION

%package dev
Summary: dev components for the perl-Test-InDistDir package.
Group: Development
Provides: perl-Test-InDistDir-devel = %{version}-%{release}
Requires: perl-Test-InDistDir = %{version}-%{release}

%description dev
dev components for the perl-Test-InDistDir package.


%package license
Summary: license components for the perl-Test-InDistDir package.
Group: Default

%description license
license components for the perl-Test-InDistDir package.


%package perl
Summary: perl components for the perl-Test-InDistDir package.
Group: Default
Requires: perl-Test-InDistDir = %{version}-%{release}

%description perl
perl components for the perl-Test-InDistDir package.


%prep
%setup -q -n Test-InDistDir-1.112071
cd %{_builddir}/Test-InDistDir-1.112071

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-InDistDir
cp %{_builddir}/Test-InDistDir-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Test-InDistDir/24a01492e7b8f3a8962b91cb6f0b4903fa119d85 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::InDistDir.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-InDistDir/24a01492e7b8f3a8962b91cb6f0b4903fa119d85

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
